services:
    application:
        image: application
        build:
            context: .
            dockerfile: dockerfiles/php/Dockerfile
        container_name: application
        working_dir: /var/www
        ports:
            - "9000:9000"
        volumes:
            - ./:/var/www:delegated
        networks:
            - application
        restart: always

    nginx:
        image: nginx:latest
        container_name: nginx
        working_dir: /var/www
        ports:
            - "8084:80"
        volumes:
            - ./dockerfiles/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./public:/var/www/public:ro
        networks:
            - application
        restart: always

    mysql:
        image: mysql:latest
        container_name: mysql
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_ALLOW_EMPTY_PASSWORD: '1'
        volumes:
            - mysql_data:/var/lib/mysql
        networks:
            - application
        restart: always

networks:
    application:
        driver: bridge

volumes:
    mysql_data:
        driver: local
